### PR TITLE
Rename catalog-info.yaml to catalog-info.yml

### PR DESCRIPTION
**Pull request by ehats**
For consistency with other repos

### CODE REVIEW

**Review by JesperTerkelsen — APPROVED** [review]

**Comment by ehats** [comment]
@Tradeshift/developer-productivity please review

**Comment by ehats** [comment]
@Tradeshift/developer-productivity please review

**Review by fardin01 — APPROVED** [review]
Any other (technical) reasons for changing the file extension, apart from consistency? 🤔

**Comment by ehats** [comment]
Having all repos use `.yml` allows us to reduce our github api usage by half when it comes to determining repo ownership

**Comment by fardin01** [comment]
> Having all repos use `.yml` allows us to reduce our github api usage by half when it comes to determining repo ownership

Because we are doing that by listing all `.yaml` files at the moment? 🤔

**Comment by ehats** [comment]
No, we look for `catalog-info.yml` , but we'd need to add a second request for the 1% of repos that went down a different path.

Another reason was also that Github actions also follows this convention, only `.yml` works, so this also aligns us with that

**Comment by sorenmat** [comment]
I guess you change it too: `org:Tradeshift filename:catalog-info+extension:yaml+extension:yml|yaml+org:Tradeshift`

**Pull request merged**
